# Generated by Django 3.2.3 on 2022-01-25 01:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriaClinica',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='Identificador de historia clínica')),
                ('fecha', models.DateField(verbose_name='Fecha de inscripción')),
                ('apellido1', models.CharField(max_length=255, verbose_name='Apellido 1')),
                ('apellido2', models.CharField(max_length=255, verbose_name='Apellido 2')),
                ('nombres', models.CharField(max_length=255, verbose_name='Nombres')),
                ('ci', models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(code='nomatch', message='Este campo debe tener 11 dígitos', regex='^.{11}$')], verbose_name='Carné de indentidad')),
            ],
            options={
                'verbose_name': 'Modelo de historia Clínica',
                'verbose_name_plural': '01 - Modelos de historia Clínica',
            },
        ),
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidad', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Unidad',
                'verbose_name_plural': '02 - Unidades',
            },
        ),
    ]
