# Generated by Django 3.2.3 on 2022-01-25 01:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_historiaclinica_unidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicamento', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Medicamento',
                'verbose_name_plural': '03 - Medicamentos',
            },
        ),
        migrations.CreateModel(
            name='Reaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaccion', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Reacción',
                'verbose_name_plural': '04 - Reacciones',
            },
        ),
        migrations.CreateModel(
            name='SensibilidadMedicamentosa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('historia_clinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.historiaclinica')),
                ('medicamento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.medicamento')),
                ('reccion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.reaccion')),
            ],
            options={
                'verbose_name': 'Sensibilidad Medicamentosa',
                'verbose_name_plural': 'Sensibilidades Medicamentosas',
            },
        ),
    ]
