# Generated by Django 3.2.3 on 2022-01-25 01:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_medicamento_reaccion_sensibilidadmedicamentosa'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicamento',
            options={'verbose_name': 'Medicamento, sangre y derivados', 'verbose_name_plural': '03 - Medicamentos, sangre y derivados'},
        ),
        migrations.AlterField(
            model_name='sensibilidadmedicamentosa',
            name='medicamento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.medicamento', verbose_name='medicamento, sangre y derivados'),
        ),
        migrations.AlterField(
            model_name='sensibilidadmedicamentosa',
            name='reccion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.reaccion', verbose_name='Reacción'),
        ),
        migrations.CreateModel(
            name='RegistroTransfusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('preparado', models.CharField(max_length=255)),
                ('numero', models.CharField(max_length=255, verbose_name='Número del frasco')),
                ('volumen', models.FloatField(verbose_name='Volúmen')),
                ('paciente', models.CharField(max_length=255)),
                ('frasco', models.CharField(max_length=255)),
                ('tecnico', models.CharField(max_length=255)),
                ('historia_clinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.historiaclinica')),
            ],
            options={
                'verbose_name': 'Registro de transfusión',
                'verbose_name_plural': 'Registro de transfusiones',
            },
        ),
    ]
