# Generated by Django 3.2.3 on 2022-01-25 01:55

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20220124_2048'),
    ]

    operations = [
        migrations.CreateModel(
            name='AspectosPSI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observaciones', ckeditor.fields.RichTextField()),
                ('historia_clinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.historiaclinica')),
            ],
            options={
                'verbose_name': 'Aspecto Sicosocial e Interrelación médico de sala-médico de la familia',
                'verbose_name_plural': 'Aspectos Sicosociales e Interrelaciones médico de sala-médico de la familia',
            },
        ),
    ]
