# Generated by Django 3.2.3 on 2022-01-25 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_aspectospsi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aspectospsi',
            name='observaciones',
            field=models.TextField(),
        ),
    ]
