# Generated by Django 3.2.3 on 2022-01-25 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_historiaenfermedad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historiaenfermedad',
            name='asma_bronquial_hijo',
            field=models.BooleanField(blank=True, null=True, verbose_name='Hijo'),
        ),
        migrations.AlterField(
            model_name='historiaenfermedad',
            name='asma_bronquial_madre',
            field=models.BooleanField(blank=True, null=True, verbose_name='Madre'),
        ),
        migrations.AlterField(
            model_name='historiaenfermedad',
            name='asma_bronquial_otro',
            field=models.BooleanField(blank=True, null=True, verbose_name='Otro'),
        ),
        migrations.AlterField(
            model_name='historiaenfermedad',
            name='asma_bronquial_padre',
            field=models.BooleanField(blank=True, null=True, verbose_name='Padre'),
        ),
        migrations.AlterField(
            model_name='historiaenfermedad',
            name='asma_bronquial_personal',
            field=models.BooleanField(blank=True, null=True, verbose_name='Personal'),
        ),
        migrations.AlterField(
            model_name='historiaenfermedad',
            name='asma_bronquial_texto',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Asma bronquial'),
        ),
        migrations.AlterField(
            model_name='historiaenfermedad',
            name='blenorragia_hijo',
            field=models.BooleanField(blank=True, null=True, verbose_name='Hijo'),
        ),
        migrations.AlterField(
            model_name='historiaenfermedad',
            name='blenorragia_madre',
            field=models.BooleanField(blank=True, null=True, verbose_name='Madre'),
        ),
        migrations.AlterField(
            model_name='historiaenfermedad',
            name='blenorragia_otro',
            field=models.BooleanField(blank=True, null=True, verbose_name='Otro'),
        ),
        migrations.AlterField(
            model_name='historiaenfermedad',
            name='blenorragia_padre',
            field=models.BooleanField(blank=True, null=True, verbose_name='Padre'),
        ),
        migrations.AlterField(
            model_name='historiaenfermedad',
            name='blenorragia_personal',
            field=models.BooleanField(blank=True, null=True, verbose_name='Personal'),
        ),
        migrations.AlterField(
            model_name='historiaenfermedad',
            name='blenorragia_texto',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Blenorragia'),
        ),
        migrations.AlterField(
            model_name='historiaenfermedad',
            name='cancer_hijo',
            field=models.BooleanField(blank=True, null=True, verbose_name='Hijo'),
        ),
        migrations.AlterField(
            model_name='historiaenfermedad',
            name='cancer_madre',
            field=models.BooleanField(blank=True, null=True, verbose_name='Madre'),
        ),
        migrations.AlterField(
            model_name='historiaenfermedad',
            name='cancer_otro',
            field=models.BooleanField(blank=True, null=True, verbose_name='Otro'),
        ),
        migrations.AlterField(
            model_name='historiaenfermedad',
            name='cancer_padre',
            field=models.BooleanField(blank=True, null=True, verbose_name='Padre'),
        ),
        migrations.AlterField(
            model_name='historiaenfermedad',
            name='cancer_personal',
            field=models.BooleanField(blank=True, null=True, verbose_name='Personal'),
        ),
        migrations.AlterField(
            model_name='historiaenfermedad',
            name='cancer_texto',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Cáncer'),
        ),
        migrations.AlterField(
            model_name='historiaenfermedad',
            name='cardiopatia_isquemica_hijo',
            field=models.BooleanField(blank=True, null=True, verbose_name='Hijo'),
        ),
        migrations.AlterField(
            model_name='historiaenfermedad',
            name='cardiopatia_isquemica_madre',
            field=models.BooleanField(blank=True, null=True, verbose_name='Madre'),
        ),
        migrations.AlterField(
            model_name='historiaenfermedad',
            name='cardiopatia_isquemica_otro',
            field=models.BooleanField(blank=True, null=True, verbose_name='Otro'),
        ),
        migrations.AlterField(
            model_name='historiaenfermedad',
            name='cardiopatia_isquemica_padre',
            field=models.BooleanField(blank=True, null=True, verbose_name='Padre'),
        ),
        migrations.AlterField(
            model_name='historiaenfermedad',
            name='cardiopatia_isquemica_personal',
            field=models.BooleanField(blank=True, null=True, verbose_name='Personal'),
        ),
        migrations.AlterField(
            model_name='historiaenfermedad',
            name='cardiopatia_isquemica_texto',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Cardiopatía isquémica'),
        ),
        migrations.AlterField(
            model_name='historiaenfermedad',
            name='dengue_hijo',
            field=models.BooleanField(blank=True, null=True, verbose_name='Hijo'),
        ),
        migrations.AlterField(
            model_name='historiaenfermedad',
            name='dengue_madre',
            field=models.BooleanField(blank=True, null=True, verbose_name='Madre'),
        ),
        migrations.AlterField(
            model_name='historiaenfermedad',
            name='dengue_otro',
            field=models.BooleanField(blank=True, null=True, verbose_name='Otro'),
        ),
        migrations.AlterField(
            model_name='historiaenfermedad',
            name='dengue_padre',
            field=models.BooleanField(blank=True, null=True, verbose_name='Padre'),
        ),
        migrations.AlterField(
            model_name='historiaenfermedad',
            name='dengue_personal',
            field=models.BooleanField(blank=True, null=True, verbose_name='Personal'),
        ),
        migrations.AlterField(
            model_name='historiaenfermedad',
            name='dengue_texto',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Dengue'),
        ),
        migrations.AlterField(
            model_name='historiaenfermedad',
            name='diabetes_mellitus_hijo',
            field=models.BooleanField(blank=True, null=True, verbose_name='Hijo'),
        ),
        migrations.AlterField(
            model_name='historiaenfermedad',
            name='diabetes_mellitus_madre',
            field=models.BooleanField(blank=True, null=True, verbose_name='Madre'),
        ),
        migrations.AlterField(
            model_name='historiaenfermedad',
            name='diabetes_mellitus_otro',
            field=models.BooleanField(blank=True, null=True, verbose_name='Otro'),
        ),
        migrations.AlterField(
            model_name='historiaenfermedad',
            name='diabetes_mellitus_padre',
            field=models.BooleanField(blank=True, null=True, verbose_name='Padre'),
        ),
        migrations.AlterField(
            model_name='historiaenfermedad',
            name='diabetes_mellitus_personal',
            field=models.BooleanField(blank=True, null=True, verbose_name='Personal'),
        ),
        migrations.AlterField(
            model_name='historiaenfermedad',
            name='diabetes_mellitus_texto',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Diabetes mellitus'),
        ),
        migrations.AlterField(
            model_name='historiaenfermedad',
            name='enfermedad_cerebro_vascular_hijo',
            field=models.BooleanField(blank=True, null=True, verbose_name='Hijo'),
        ),
        migrations.AlterField(
            model_name='historiaenfermedad',
            name='enfermedad_cerebro_vascular_madre',
            field=models.BooleanField(blank=True, null=True, verbose_name='Madre'),
        ),
        migrations.AlterField(
            model_name='historiaenfermedad',
            name='enfermedad_cerebro_vascular_otro',
            field=models.BooleanField(blank=True, null=True, verbose_name='Otro'),
        ),
        migrations.AlterField(
            model_name='historiaenfermedad',
            name='enfermedad_cerebro_vascular_padre',
            field=models.BooleanField(blank=True, null=True, verbose_name='Padre'),
        ),
        migrations.AlterField(
            model_name='historiaenfermedad',
            name='enfermedad_cerebro_vascular_personal',
            field=models.BooleanField(blank=True, null=True, verbose_name='Personal'),
        ),
        migrations.AlterField(
            model_name='historiaenfermedad',
            name='enfermedad_cerebro_vascular_texto',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Enfermedad cerebro vascular'),
        ),
        migrations.AlterField(
            model_name='historiaenfermedad',
            name='epilepsia_hijo',
            field=models.BooleanField(blank=True, null=True, verbose_name='Hijo'),
        ),
        migrations.AlterField(
            model_name='historiaenfermedad',
            name='epilepsia_madre',
            field=models.BooleanField(blank=True, null=True, verbose_name='Madre'),
        ),
        migrations.AlterField(
            model_name='historiaenfermedad',
            name='epilepsia_otro',
            field=models.BooleanField(blank=True, null=True, verbose_name='Otro'),
        ),
        migrations.AlterField(
            model_name='historiaenfermedad',
            name='epilepsia_padre',
            field=models.BooleanField(blank=True, null=True, verbose_name='Padre'),
        ),
        migrations.AlterField(
            model_name='historiaenfermedad',
            name='epilepsia_personal',
            field=models.BooleanField(blank=True, null=True, verbose_name='Personal'),
        ),
        migrations.AlterField(
            model_name='historiaenfermedad',
            name='epilepsia_texto',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Epilepsia'),
        ),
        migrations.AlterField(
            model_name='historiaenfermedad',
            name='hepatitis_viral_hijo',
            field=models.BooleanField(blank=True, null=True, verbose_name='Hijo'),
        ),
        migrations.AlterField(
            model_name='historiaenfermedad',
            name='hepatitis_viral_madre',
            field=models.BooleanField(blank=True, null=True, verbose_name='Madre'),
        ),
        migrations.AlterField(
            model_name='historiaenfermedad',
            name='hepatitis_viral_otro',
            field=models.BooleanField(blank=True, null=True, verbose_name='Otro'),
        ),
        migrations.AlterField(
            model_name='historiaenfermedad',
            name='hepatitis_viral_padre',
            field=models.BooleanField(blank=True, null=True, verbose_name='Padre'),
        ),
        migrations.AlterField(
            model_name='historiaenfermedad',
            name='hepatitis_viral_personal',
            field=models.BooleanField(blank=True, null=True, verbose_name='Personal'),
        ),
        migrations.AlterField(
            model_name='historiaenfermedad',
            name='hepatitis_viral_texto',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Hepatitis viral'),
        ),
        migrations.AlterField(
            model_name='historiaenfermedad',
            name='hipertension_arterial_hijo',
            field=models.BooleanField(blank=True, null=True, verbose_name='Hijo'),
        ),
        migrations.AlterField(
            model_name='historiaenfermedad',
            name='hipertension_arterial_madre',
            field=models.BooleanField(blank=True, null=True, verbose_name='Madre'),
        ),
        migrations.AlterField(
            model_name='historiaenfermedad',
            name='hipertension_arterial_otro',
            field=models.BooleanField(blank=True, null=True, verbose_name='Otro'),
        ),
        migrations.AlterField(
            model_name='historiaenfermedad',
            name='hipertension_arterial_padre',
            field=models.BooleanField(blank=True, null=True, verbose_name='Padre'),
        ),
        migrations.AlterField(
            model_name='historiaenfermedad',
            name='hipertension_arterial_personal',
            field=models.BooleanField(blank=True, null=True, verbose_name='Personal'),
        ),
        migrations.AlterField(
            model_name='historiaenfermedad',
            name='hipertension_arterial_texto',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Hipertensión arterial'),
        ),
        migrations.AlterField(
            model_name='historiaenfermedad',
            name='otras_hijo',
            field=models.BooleanField(blank=True, null=True, verbose_name='Hijo'),
        ),
        migrations.AlterField(
            model_name='historiaenfermedad',
            name='otras_madre',
            field=models.BooleanField(blank=True, null=True, verbose_name='Madre'),
        ),
        migrations.AlterField(
            model_name='historiaenfermedad',
            name='otras_otro',
            field=models.BooleanField(blank=True, null=True, verbose_name='Otro'),
        ),
        migrations.AlterField(
            model_name='historiaenfermedad',
            name='otras_padre',
            field=models.BooleanField(blank=True, null=True, verbose_name='Padre'),
        ),
        migrations.AlterField(
            model_name='historiaenfermedad',
            name='otras_personal',
            field=models.BooleanField(blank=True, null=True, verbose_name='Personal'),
        ),
        migrations.AlterField(
            model_name='historiaenfermedad',
            name='otras_texto',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Otras'),
        ),
        migrations.AlterField(
            model_name='historiaenfermedad',
            name='sifilis_hijo',
            field=models.BooleanField(blank=True, null=True, verbose_name='Hijo'),
        ),
        migrations.AlterField(
            model_name='historiaenfermedad',
            name='sifilis_madre',
            field=models.BooleanField(blank=True, null=True, verbose_name='Madre'),
        ),
        migrations.AlterField(
            model_name='historiaenfermedad',
            name='sifilis_otro',
            field=models.BooleanField(blank=True, null=True, verbose_name='Otro'),
        ),
        migrations.AlterField(
            model_name='historiaenfermedad',
            name='sifilis_padre',
            field=models.BooleanField(blank=True, null=True, verbose_name='Padre'),
        ),
        migrations.AlterField(
            model_name='historiaenfermedad',
            name='sifilis_personal',
            field=models.BooleanField(blank=True, null=True, verbose_name='Personal'),
        ),
        migrations.AlterField(
            model_name='historiaenfermedad',
            name='sifilis_texto',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Sífilis'),
        ),
        migrations.AlterField(
            model_name='historiaenfermedad',
            name='tuberculosis_hijo',
            field=models.BooleanField(blank=True, null=True, verbose_name='Hijo'),
        ),
        migrations.AlterField(
            model_name='historiaenfermedad',
            name='tuberculosis_madre',
            field=models.BooleanField(blank=True, null=True, verbose_name='Madre'),
        ),
        migrations.AlterField(
            model_name='historiaenfermedad',
            name='tuberculosis_otro',
            field=models.BooleanField(blank=True, null=True, verbose_name='Otro'),
        ),
        migrations.AlterField(
            model_name='historiaenfermedad',
            name='tuberculosis_padre',
            field=models.BooleanField(blank=True, null=True, verbose_name='Padre'),
        ),
        migrations.AlterField(
            model_name='historiaenfermedad',
            name='tuberculosis_personal',
            field=models.BooleanField(blank=True, null=True, verbose_name='Personal'),
        ),
        migrations.AlterField(
            model_name='historiaenfermedad',
            name='tuberculosis_texto',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tuberculosis'),
        ),
    ]
