# Generated by Django 3.2.3 on 2022-01-25 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20220124_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='historiaenfermedad',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historiaenfermedad',
            name='secuelas',
            field=models.TextField(blank=True, null=True, verbose_name='Secuelas'),
        ),
        migrations.AddField(
            model_name='historiaenfermedad',
            name='tipo_operacion',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tipo de operación'),
        ),
    ]
