# Generated by Django 3.2.3 on 2022-02-02 04:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20220124_2230'),
    ]

    operations = [
        migrations.CreateModel(
            name='TAC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('directorio', models.CharField(max_length=500)),
                ('historia_clinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.historiaclinica')),
            ],
            options={
                'verbose_name': 'Tomografía axial computarizada',
                'verbose_name_plural': 'Tomografías axiales computarizadas',
            },
        ),
    ]
