# Generated by Django 3.2.3 on 2022-02-02 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_tac'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tac',
            options={'verbose_name': 'Tomografía axial computarizada', 'verbose_name_plural': '05 - Tomografías axiales computarizadas'},
        ),
        migrations.AddField(
            model_name='tac',
            name='cant',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tac',
            name='directorio',
            field=models.FilePathField(allow_files=False, allow_folders=True),
        ),
    ]
