# Generated by Django 3.2.3 on 2022-02-02 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20220201_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tac',
            name='directorio',
            field=models.FilePathField(allow_files=False, allow_folders=True, path='/'),
        ),
    ]
