# Generated by Django 3.2.3 on 2022-02-02 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_tac_directorio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tac',
            name='cant',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='tac',
            name='directorio',
            field=models.FileField(upload_to='TAC/'),
        ),
    ]
