# Generated by Django 3.2.3 on 2022-02-02 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20220201_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tac',
            name='historia_clinica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.historiaclinica'),
        ),
    ]
