# Generated by Django 3.2.3 on 2022-02-14 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_tac_historia_clinica'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReactantesFaseAguda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proteinascr', models.FloatField()),
                ('leucocitos_neutrofilo', models.FloatField()),
                ('ferritina', models.FloatField()),
            ],
            options={
                'verbose_name': 'Reactante de fase aguda',
                'verbose_name_plural': 'Reactantes de fase aguda',
            },
        ),
        migrations.CreateModel(
            name='TipoVacuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Tipo de vacuna',
                'verbose_name_plural': 'Tipos de vacuna',
            },
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='edad',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='genero',
            field=models.CharField(choices=[('m', 'Masculino'), ('f', 'Femenino')], default='m', max_length=255),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Vacuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosis', models.IntegerField()),
                ('fecha', models.DateField()),
                ('hc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacunas', to='core.historiaclinica')),
                ('tipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.tipovacuna')),
            ],
            options={
                'verbose_name': 'Vacuna',
                'verbose_name_plural': 'Vacunas',
            },
        ),
        migrations.CreateModel(
            name='MedicamentosNacionales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('hc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicamentos_nacionales', to='core.historiaclinica')),
            ],
            options={
                'verbose_name': 'Medicamento nacional',
                'verbose_name_plural': 'Medicamentos nacionales',
            },
        ),
        migrations.CreateModel(
            name='Fecha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('1', 'Positivo'), ('2', 'Ingreso'), ('3', 'Defuncion')], max_length=255)),
                ('fecha', models.DateField()),
                ('notas', models.TextField()),
                ('hc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fechas', to='core.historiaclinica')),
            ],
            options={
                'verbose_name': 'Fecha',
                'verbose_name_plural': 'Fechas',
            },
        ),
        migrations.CreateModel(
            name='EstudioRadiologico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('1', 'Rayos X'), ('2', 'TAC')], max_length=255)),
                ('imagen', models.FileField(upload_to='imagenes/')),
                ('fecha', models.DateField()),
                ('hc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estudios_radiologicos', to='core.historiaclinica')),
            ],
            options={
                'verbose_name': 'Estudio radiológico',
                'verbose_name_plural': 'Estudios radiológicos',
            },
        ),
        migrations.CreateModel(
            name='Comorbilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comorbilidad', models.CharField(max_length=255)),
                ('hc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comorbilidades', to='core.historiaclinica')),
            ],
            options={
                'verbose_name': 'Comorbilidad',
                'verbose_name_plural': 'Comorbilidades',
            },
        ),
    ]
