# Generated by Django 3.2.3 on 2022-02-14 02:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20220213_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='reactantesfaseaguda',
            name='hc',
            field=models.ForeignKey(default='843241042917237', on_delete=django.db.models.deletion.CASCADE, related_name='reactantes', to='core.historiaclinica'),
            preserve_default=False,
        ),
    ]
