# Generated by Django 4.0.5 on 2022-12-15 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_reactantesfaseaguda_hc'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aspectospsi',
            options={'verbose_name': 'Aspecto Psicosocial e Interrelación médico de sala-médico de la familia', 'verbose_name_plural': 'Aspectos Psicosociales e Interrelaciones médico de sala-médico de la familia'},
        ),
        migrations.AlterModelOptions(
            name='historiaclinica',
            options={'verbose_name': 'Modelo de historia Clínica', 'verbose_name_plural': 'Modelos de historia Clínica'},
        ),
        migrations.AlterModelOptions(
            name='medicamento',
            options={'verbose_name': 'Medicamento, sangre y derivados', 'verbose_name_plural': 'Medicamentos, sangre y derivados'},
        ),
        migrations.AlterModelOptions(
            name='reaccion',
            options={'verbose_name': 'Reacción', 'verbose_name_plural': 'Reacciones'},
        ),
        migrations.AlterModelOptions(
            name='tac',
            options={'verbose_name': 'Imagen de Radiología Digital', 'verbose_name_plural': 'Imágenes de Radiologías Digitales'},
        ),
        migrations.AlterModelOptions(
            name='unidad',
            options={'verbose_name': 'Unidad', 'verbose_name_plural': 'Unidades'},
        ),
    ]
